version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bd-post
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crud-test
      POSTGRES_DB: crud

  api:
    build:
      context: ./crud-backend
      dockerfile: Dockerfile
    container_name: crud-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: crud-test
      DB_NAME: crud
    depends_on:
      - db

  frontend:
    build:
      context: ./crud-frontend
      dockerfile: Dockerfile
    container_name: crud-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - api

volumes:
  pgdata:
